apiVersion: v1
kind: Service
metadata:
  name: {{ include "interop.backend.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "interop.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.service.backend.type }}
  ports:
    - port: {{ .Values.service.backend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "interop.backend.selectorLabels" . | nindent 4 }}
