// Generated by scripts/sync-skills-docs.mjs — do not edit by hand.

export const SKILLS_NAV = {
  group: 'Agent Skills',
  sectionId: 'agent-skills',
  items: [
    { id: 'skills-overview', label: 'Overview' },
    { id: 'skills-quickstart', label: 'Quickstart' },
    { id: 'skills-specification', label: 'Specification' },
    { id: 'skills-agent-integration', label: 'Agent integration' },
    { id: 'skills-best-practices', label: 'Best practices' },
    { id: 'skills-descriptions', label: 'Skill descriptions' },
    { id: 'skills-scripts', label: 'Using scripts' },
    { id: 'skills-evaluating', label: 'Evaluating skills' },
  ],
} as const;

export const SKILLS_ARTICLES = [
  {
    id: 'skills-overview',
    section: 'agent-skills',
    title: "Agent Skills Overview",
    navLabel: "Overview",
    readTime: 3,
    updatedAt: '2026-06-01',
    lead: "A standardized way to give AI agents new capabilities and expertise.",
    body: `<h2 id="what-are-agent-skills" class="doc-h2">What are Agent Skills?</h2>
<p class="doc-p">Agent Skills are a lightweight, open format for extending AI agent capabilities with specialized knowledge and workflows.</p>
<p class="doc-p">At its core, a skill is a folder containing a <code>SKILL.md</code> file. This file includes metadata (<code>name</code> and <code>description</code>, at minimum) and instructions that tell an agent how to perform a specific task. Skills can also bundle scripts, reference materials, templates, and other resources.</p>
<div class="codeblock"><pre><code>my-skill/
├── SKILL.md          # Required: metadata + instructions
├── scripts/          # Optional: executable code
├── references/       # Optional: documentation
├── assets/           # Optional: templates, resources
└── ...               # Any additional files or directories
</code></pre></div>
<h2 id="why-agent-skills" class="doc-h2">Why Agent Skills?</h2>
<p class="doc-p">Agents are increasingly capable, but often don&#39;t have the context they need to do real work reliably. Skills solve this by packaging procedural knowledge and company-, team-, and user-specific context into portable, version-controlled folders that agents load on demand. This gives agents:</p>
<ul class="doc-list">
<li><strong>Domain expertise</strong>: Capture specialized knowledge — from legal review processes to data analysis pipelines to presentation formatting — as reusable instructions and resources.</li>
<li><strong>Repeatable workflows</strong>: Turn multi-step tasks into consistent, auditable procedures.</li>
<li><strong>Cross-product reuse</strong>: Build a skill once and use it across any skills-compatible agent.</li>
</ul>
<h2 id="how-do-agent-skills-work" class="doc-h2">How do Agent Skills work?</h2>
<p class="doc-p">Agents load skills through <strong>progressive disclosure</strong>, in three stages:</p>
<ol class="doc-steps">
<li><p class="doc-p"><strong>Discovery</strong>: At startup, agents load only the name and description of each available skill, just enough to know when it might be relevant.</p>
</li>
<li><p class="doc-p"><strong>Activation</strong>: When a task matches a skill&#39;s description, the agent reads the full <code>SKILL.md</code> instructions into context.</p>
</li>
<li><p class="doc-p"><strong>Execution</strong>: The agent follows the instructions, optionally executing bundled code or loading referenced files as needed.</p>
</li>
</ol>
<p class="doc-p">Full instructions load only when a task calls for them, so agents can keep many skills on hand with only a small context footprint.</p>
<h2 id="where-can-i-use-agent-skills" class="doc-h2">Where can I use Agent Skills?</h2>
<p class="doc-p">Agent Skills are supported by a large number of AI tools and agentic clients — see the <a href="https://agentskills.io/clients" class="doc-link">Client Showcase</a> to explore some of them!</p>
<h2 id="open-development" class="doc-h2">Open development</h2>
<p class="doc-p">The Agent Skills format was originally developed by <a href="https://www.anthropic.com/" class="doc-link">Anthropic</a>, released as an open standard, and has been adopted by a growing number of agent products. The standard is open to contributions from the broader ecosystem.</p>
<p class="doc-p">Come join the discussion on <a href="https://github.com/agentskills/agentskills" class="doc-link">GitHub</a> or <a href="https://discord.gg/MKPE9g8aUy" class="doc-link">Discord</a>!</p>
<h2 id="get-started-with-agent-skills" class="doc-h2">Get started with Agent Skills</h2>
<div class="doc-cards"><a href="/docs/skills-quickstart" class="doc-card"><div class="doc-card-t">Quickstart</div><div class="doc-card-b">Create your first Agent Skill and see it in action.</div></a><a href="/docs/skills-specification" class="doc-card"><div class="doc-card-t">Specification</div><div class="doc-card-b">The complete format specification for Agent Skills.</div></a></div>`,
  },
  {
    id: 'skills-quickstart',
    section: 'agent-skills',
    title: "Quickstart",
    navLabel: "Quickstart",
    readTime: 3,
    updatedAt: '2026-06-01',
    lead: "Create your first Agent Skill and see it work in VS Code.",
    body: `<h2 id="prerequisites" class="doc-h2">Prerequisites</h2>
<ul class="doc-list">
<li><a href="https://code.visualstudio.com/" class="doc-link">VS Code</a> with <a href="https://marketplace.visualstudio.com/items?itemName=GitHub.copilot" class="doc-link">GitHub Copilot</a></li>
</ul>
<div class="callout doc-callout">This tutorial uses VS Code, but Agent Skills are an open format. The same skill works in any compatible agent, including Claude Code and OpenAI Codex.</div>



<h2 id="create-the-skill" class="doc-h2">Create the skill</h2>
<p class="doc-p">A skill is a folder containing a <code>SKILL.md</code> file. VS Code looks for skills in <code>.agents/skills/</code> by default. Create <code>.agents/skills/roll-dice/SKILL.md</code> in your project:</p>
<div class="codeblock"><pre><code class="language-markdown">---
name: roll-dice
description: Roll dice using a random number generator. Use when asked to roll a die (d6, d20, etc.), roll dice, or generate a random dice roll.
---

To roll a die, use the following command that generates a random number from 1
to the given number of sides:

\`\`\`bash
echo $((RANDOM % &lt;sides&gt; + 1))
\`\`\`

\`\`\`powershell
Get-Random -Minimum 1 -Maximum (&lt;sides&gt; + 1)
\`\`\`

Replace \`&lt;sides&gt;\` with the number of sides on the die (e.g., 6 for a standard
die, 20 for a d20).
</code></pre></div>
<p class="doc-p">That&#39;s it — one file, under 20 lines. Here&#39;s what each part does:</p>
<ul class="doc-list">
<li><strong><code>name</code></strong> — A short identifier for the skill. Must match the folder name.</li>
<li><strong><code>description</code></strong> — Tells the agent when to use this skill. This is how the agent decides whether to activate it.</li>
<li><strong>The body</strong> — Instructions the agent follows when the skill activates. Here, the agent is instructed to generate a random number using a terminal command, substituting the number of sides from the user&#39;s request.</li>
</ul>
<h2 id="try-it-out" class="doc-h2">Try it out</h2>
<ol class="doc-steps">
<li>Open your project in VS Code.</li>
<li>Open the Copilot Chat panel.</li>
<li>Select <strong>Agent</strong> mode from the mode dropdown at the bottom of the chat panel.</li>
<li>Type <code>/skills</code> to confirm that <code>roll-dice</code> appears in the list. If it doesn&#39;t, check that the file is at <code>.agents/skills/roll-dice/SKILL.md</code> relative to your project root.</li>
<li>Ask: <strong>&quot;Roll a d20&quot;</strong></li>
</ol>
<p class="doc-p">The agent should activate the <code>roll-dice</code> skill. It may ask for permission to run a terminal command — allow it. It will run the command and return a random number between 1 and 20.</p>
<div class="callout doc-callout">Tool-use reliability varies across models — some follow skill instructions and run commands consistently, while others may attempt to answer on their own. If the agent responds without running a terminal command, try selecting a different model from the model dropdown.</div>



<h2 id="how-it-works" class="doc-h2">How it works</h2>
<p class="doc-p">Here&#39;s what happened behind the scenes:</p>
<ol class="doc-steps">
<li><p class="doc-p"><strong>Discovery</strong> — When the chat session started, the agent scanned default skill directories and found your skill. It read only the <code>name</code> and <code>description</code>, just enough to know when the skill might be relevant.</p>
</li>
<li><p class="doc-p"><strong>Activation</strong> — When you asked about rolling dice, the agent matched your question to the skill&#39;s description and loaded the full <code>SKILL.md</code> body into context.</p>
</li>
<li><p class="doc-p"><strong>Execution</strong> — The agent followed the instructions in the body, adapting the terminal command to the number of sides in your request.</p>
</li>
</ol>
<p class="doc-p">This process uses <strong>progressive disclosure</strong> to let the agent access many skills without loading all their instructions up front.</p>
<h2 id="next-steps" class="doc-h2">Next steps</h2>
<p class="doc-p">You&#39;ve created a working Agent Skill. From here:</p>
<ul class="doc-list">
<li><strong><a href="/docs/skills-best-practices" class="doc-link">Best practices</a></strong> — How to write skills that are well-scoped and effective.</li>
<li><strong><a href="/docs/skills-descriptions" class="doc-link">Optimizing skill descriptions</a></strong> — Test and improve your skill&#39;s description so it activates on the right prompts.</li>
<li><strong><a href="/docs/skills-specification" class="doc-link">Specification</a></strong> — The complete format reference for <code>SKILL.md</code> files.</li>
<li><strong><a href="https://github.com/anthropics/skills" class="doc-link">Example skills</a></strong> — Browse real-world skills on GitHub.</li>
</ul>
`,
  },
  {
    id: 'skills-specification',
    section: 'agent-skills',
    title: "Specification",
    navLabel: "Specification",
    readTime: 3,
    updatedAt: '2026-06-01',
    lead: "The complete format specification for Agent Skills.",
    body: `<h2 id="directory-structure" class="doc-h2">Directory structure</h2>
<p class="doc-p">A skill is a directory containing, at minimum, a <code>SKILL.md</code> file:</p>
<div class="codeblock"><pre><code>skill-name/
├── SKILL.md          # Required: metadata + instructions
├── scripts/          # Optional: executable code
├── references/       # Optional: documentation
├── assets/           # Optional: templates, resources
└── ...               # Any additional files or directories
</code></pre></div>
<h2><code>SKILL.md</code> format</h2>
<p class="doc-p">The <code>SKILL.md</code> file must contain YAML frontmatter followed by Markdown content.</p>
<h3 class="doc-h3">Frontmatter</h3>
<div class="doc-table-wrap"><table class="doc-table">
<thead>
<tr>
<th>Field</th>
<th>Required</th>
<th>Constraints</th>
</tr>
</thead>
<tbody><tr>
<td><code>name</code></td>
<td>Yes</td>
<td>Max 64 characters. Lowercase letters, numbers, and hyphens only. Must not start or end with a hyphen.</td>
</tr>
<tr>
<td><code>description</code></td>
<td>Yes</td>
<td>Max 1024 characters. Non-empty. Describes what the skill does and when to use it.</td>
</tr>
<tr>
<td><code>license</code></td>
<td>No</td>
<td>License name or reference to a bundled license file.</td>
</tr>
<tr>
<td><code>compatibility</code></td>
<td>No</td>
<td>Max 500 characters. Indicates environment requirements (intended product, system packages, network access, etc.).</td>
</tr>
<tr>
<td><code>metadata</code></td>
<td>No</td>
<td>Arbitrary key-value mapping for additional metadata.</td>
</tr>
<tr>
<td><code>allowed-tools</code></td>
<td>No</td>
<td>Space-separated string of pre-approved tools the skill may use. (Experimental)</td>
</tr>
</tbody></table></div>
<div class="callout doc-callout">**Minimal example:**

<div class="codeblock"><pre><code class="language-markdown">skills-ref validate ./my-skill
</code></pre></div>
<p class="doc-p">This checks that your <code>SKILL.md</code> frontmatter is valid and follows all naming conventions.</p>
`,
  },
  {
    id: 'skills-agent-integration',
    section: 'agent-skills',
    title: "How to add skills support to your agent",
    navLabel: "Agent integration",
    readTime: 7,
    updatedAt: '2026-06-01',
    lead: "A guide for adding Agent Skills support to an AI agent or development tool.",
    body: `<h2 id="the-core-principle-progressive-disclosure" class="doc-h2">The core principle: progressive disclosure</h2>
<p class="doc-p">Every skills-compatible agent follows the same three-tier loading strategy:</p>
<div class="doc-table-wrap"><table class="doc-table">
<thead>
<tr>
<th>Tier</th>
<th>What&#39;s loaded</th>
<th>When</th>
<th>Token cost</th>
</tr>
</thead>
<tbody><tr>
<td>1. Catalog</td>
<td>Name + description</td>
<td>Session start</td>
<td>~50-100 tokens per skill</td>
</tr>
<tr>
<td>2. Instructions</td>
<td>Full <code>SKILL.md</code> body</td>
<td>When the skill is activated</td>
<td>&lt;5000 tokens (recommended)</td>
</tr>
<tr>
<td>3. Resources</td>
<td>Scripts, references, assets</td>
<td>When the instructions reference them</td>
<td>Varies</td>
</tr>
</tbody></table></div>
<p class="doc-p">The model sees the catalog from the start, so it knows what skills are available. When it decides a skill is relevant, it loads the full instructions. If those instructions reference supporting files, the model loads them individually as needed.</p>
<p class="doc-p">This keeps the base context small while giving the model access to specialized knowledge on demand. An agent with 20 installed skills doesn&#39;t pay the token cost of 20 full instruction sets upfront — only the ones actually used in a given conversation.</p>
<h2 id="step-1-discover-skills" class="doc-h2">Step 1: Discover skills</h2>
<p class="doc-p">At session startup, find all available skills and load their metadata.</p>
<h3 class="doc-h3">Where to scan</h3>
<p class="doc-p">Which directories you scan depends on your agent&#39;s environment. Most locally-running agents scan at least two scopes:</p>
<ul class="doc-list">
<li><strong>Project-level</strong> (relative to the working directory): Skills specific to a project or repository.</li>
<li><strong>User-level</strong> (relative to the home directory): Skills available across all projects for a given user.</li>
</ul>
<p class="doc-p">Other scopes are possible too — for example, organization-wide skills deployed by an admin, or skills bundled with the agent itself. The right set of scopes depends on your agent&#39;s deployment model.</p>
<p class="doc-p">Within each scope, consider scanning both a <strong>client-specific directory</strong> and the <strong><code>.agents/skills/</code> convention</strong>:</p>
<div class="doc-table-wrap"><table class="doc-table">
<thead>
<tr>
<th>Scope</th>
<th>Path</th>
<th>Purpose</th>
</tr>
</thead>
<tbody><tr>
<td>Project</td>
<td><code>&lt;project&gt;/.&lt;your-client&gt;/skills/</code></td>
<td>Your client&#39;s native location</td>
</tr>
<tr>
<td>Project</td>
<td><code>&lt;project&gt;/.agents/skills/</code></td>
<td>Cross-client interoperability</td>
</tr>
<tr>
<td>User</td>
<td><code>~/.&lt;your-client&gt;/skills/</code></td>
<td>Your client&#39;s native location</td>
</tr>
<tr>
<td>User</td>
<td><code>~/.agents/skills/</code></td>
<td>Cross-client interoperability</td>
</tr>
</tbody></table></div>
<p class="doc-p">The <code>.agents/skills/</code> paths have emerged as a widely-adopted convention for cross-client skill sharing. While the Agent Skills specification does not mandate where skill directories live (it only defines what goes inside them), scanning <code>.agents/skills/</code> means skills installed by other compliant clients are automatically visible to yours, and vice versa.</p>
<div class="callout doc-callout">Some implementations also scan \`.claude/skills/\` (both project-level and user-level) for pragmatic compatibility, since many existing skills are installed there. Other additional locations include ancestor directories up to the git root (useful for monorepos), [XDG](https://specifications.freedesktop.org/basedir-spec/latest/) config directories, and user-configured paths.</div>



<h3 class="doc-h3">What to scan for</h3>
<p class="doc-p">Within each skills directory, look for <strong>subdirectories containing a file named exactly <code>SKILL.md</code></strong>:</p>
<div class="codeblock"><pre><code>~/.agents/skills/
├── pdf-processing/
│   ├── SKILL.md          ← discovered
│   └── scripts/
│       └── extract.py
├── data-analysis/
│   └── SKILL.md          ← discovered
└── README.md             ← ignored (not a skill directory)
</code></pre></div>
<p class="doc-p">Practical scanning rules:</p>
<ul class="doc-list">
<li>Skip directories that won&#39;t contain skills, such as <code>.git/</code> and <code>node_modules/</code></li>
<li>Optionally respect <code>.gitignore</code> to avoid scanning build artifacts</li>
<li>Set reasonable bounds (e.g., max depth of 4-6 levels, max 2000 directories) to prevent runaway scanning in large directory trees</li>
</ul>
<h3 class="doc-h3">Handling name collisions</h3>
<p class="doc-p">When two skills share the same <code>name</code>, apply a deterministic precedence rule.</p>
<p class="doc-p">The universal convention across existing implementations: <strong>project-level skills override user-level skills.</strong></p>
<p class="doc-p">Within the same scope (e.g., two skills named <code>code-review</code> found under both <code>&lt;project&gt;/.agents/skills/</code> and <code>&lt;project&gt;/.&lt;your-client&gt;/skills/</code>), either first-found or last-found is acceptable — pick one and be consistent. Log a warning when a collision occurs so the user knows a skill was shadowed.</p>
<h3 class="doc-h3">Trust considerations</h3>
<p class="doc-p">Project-level skills come from the repository being worked on, which may be untrusted (e.g., a freshly cloned open-source project). Consider gating project-level skill loading on a trust check — only load them if the user has marked the project folder as trusted. This prevents untrusted repositories from silently injecting instructions into the agent&#39;s context.</p>
<h3 class="doc-h3">Cloud-hosted and sandboxed agents</h3>
<p class="doc-p">If your agent runs in a container or on a remote server, it won&#39;t have access to the user&#39;s local filesystem. Discovery needs to work differently depending on the skill scope:</p>
<ul class="doc-list">
<li><strong>Project-level skills</strong> are often the easiest case. If the agent operates on a cloned repository (even inside a sandbox), project-level skills travel with the code and can be scanned from the repo&#39;s directory tree.</li>
<li><strong>User-level and organization-level skills</strong> don&#39;t exist in the sandbox. You&#39;ll need to provision them from an external source — for example, cloning a configuration repository, accepting skill URLs or packages through your agent&#39;s settings, or letting users upload skill directories through a web UI.</li>
<li><strong>Built-in skills</strong> can be packaged as static assets within the agent&#39;s deployment artifact, making them available in every session without external fetching.</li>
</ul>
<p class="doc-p">Once skills are available to the agent, the rest of the lifecycle — parsing, disclosure, activation — works the same.</p>
<h2>Step 2: Parse <code>SKILL.md</code> files</h2>
<p class="doc-p">For each discovered <code>SKILL.md</code>, extract the metadata and body content.</p>
<h3 class="doc-h3">Frontmatter extraction</h3>
<p class="doc-p">A <code>SKILL.md</code> file has two parts: YAML frontmatter between <code>---</code> delimiters, and a markdown body after the closing delimiter. To parse:</p>
<ol class="doc-steps">
<li>Find the opening <code>---</code> at the start of the file and the closing <code>---</code> after it.</li>
<li>Parse the YAML block between them. Extract <code>name</code> and <code>description</code> (required), plus any optional fields.</li>
<li>Everything after the closing <code>---</code>, trimmed, is the skill&#39;s body content.</li>
</ol>
<p class="doc-p">See the <a href="/docs/skills-specification" class="doc-link">specification</a> for the full set of frontmatter fields and their constraints.</p>
<h3 class="doc-h3">Handling malformed YAML</h3>
<p class="doc-p">Skill files authored for other clients may contain technically invalid YAML that their parsers happen to accept. The most common issue is unquoted values containing colons:</p>
<div class="codeblock"><pre><code class="language-yaml">&lt;skill_content name=&quot;pdf-processing&quot;&gt;
# PDF Processing

## When to use this skill
Use this skill when the user needs to work with PDF files...

[rest of SKILL.md body]

Skill directory: /home/user/.agents/skills/pdf-processing
Relative paths in this skill are relative to the skill directory.

&lt;skill_resources&gt;
  &lt;file&gt;scripts/extract.py&lt;/file&gt;
  &lt;file&gt;scripts/merge.py&lt;/file&gt;
  &lt;file&gt;references/pdf-spec-summary.md&lt;/file&gt;
&lt;/skill_resources&gt;
&lt;/skill_content&gt;
</code></pre></div>
<p class="doc-p">This has practical benefits:</p>
<ul class="doc-list">
<li>The model can clearly distinguish skill instructions from other conversation content</li>
<li>The harness can identify skill content during context compaction (<a href="#step-5-manage-skill-context-over-time#step-5-manage-skill-context-over-time" class="doc-link">Step 5</a>)</li>
<li>Bundled resources are surfaced to the model without being eagerly loaded</li>
</ul>
<h3 class="doc-h3">Listing bundled resources</h3>
<p class="doc-p">When a dedicated activation tool returns skill content, it can also enumerate supporting files (scripts, references, assets) in the skill directory — but it should <strong>not eagerly read them</strong>. The model loads specific files on demand using its file-read tools when the skill&#39;s instructions reference them.</p>
<p class="doc-p">For large skill directories, consider capping the listing and noting that it may be incomplete.</p>
<h3 class="doc-h3">Permission allowlisting</h3>
<p class="doc-p">If your agent has a permission system that gates file access, <strong>allowlist skill directories</strong> so the model can read bundled resources without triggering user confirmation prompts. Without this, every reference to a bundled script or reference file results in a permission dialog, breaking the flow for skills that include resources beyond the <code>SKILL.md</code> itself.</p>
<h2 id="step-5-manage-skill-context-over-time" class="doc-h2">Step 5: Manage skill context over time</h2>
<p class="doc-p">Once skill instructions are in the conversation context, keep them effective for the duration of the session.</p>
<h3 class="doc-h3">Protect skill content from context compaction</h3>
<p class="doc-p">If your agent truncates or summarizes older messages when the context window fills up, <strong>exempt skill content from pruning</strong>. Skill instructions are durable behavioral guidance — losing them mid-conversation silently degrades the agent&#39;s performance without any visible error. The model continues operating but without the specialized instructions the skill provided.</p>
<p class="doc-p">Common approaches:</p>
<ul class="doc-list">
<li>Flag skill tool outputs as protected so the pruning algorithm skips them</li>
<li>Use the <a href="#structured-wrapping#structured-wrapping" class="doc-link">structured tags</a> from Step 4 to identify skill content and preserve it during compaction</li>
</ul>
<h3 class="doc-h3">Deduplicate activations</h3>
<p class="doc-p">Consider tracking which skills have been activated in the current session. If the model (or user) attempts to load a skill that&#39;s already in context, you can skip the re-injection to avoid the same instructions appearing multiple times in the conversation.</p>
<h3 class="doc-h3">Subagent delegation (optional)</h3>
<p class="doc-p">This is an advanced pattern only supported by some clients. Instead of injecting skill instructions into the main conversation, the skill is run in a <strong>separate subagent session</strong>. The subagent receives the skill instructions, performs the task, and returns a summary of its work to the main conversation.</p>
<p class="doc-p">This pattern is useful when a skill&#39;s workflow is complex enough to benefit from a dedicated, focused session.</p>
`,
  },
  {
    id: 'skills-best-practices',
    section: 'agent-skills',
    title: "Best practices for skill creators",
    navLabel: "Best practices",
    readTime: 4,
    updatedAt: '2026-06-01',
    lead: "How to write skills that are well-scoped and calibrated to the task.",
    body: `<h2 id="start-from-real-expertise" class="doc-h2">Start from real expertise</h2>
<p class="doc-p">A common pitfall in skill creation is asking an LLM to generate a skill without providing domain-specific context — relying solely on the LLM&#39;s general training knowledge. The result is vague, generic procedures (&quot;handle errors appropriately,&quot; &quot;follow best practices for authentication&quot;) rather than the specific API patterns, edge cases, and project conventions that make a skill valuable.</p>
<p class="doc-p">Effective skills are grounded in real expertise. The key is feeding domain-specific context into the creation process.</p>
<h3 class="doc-h3">Extract from a hands-on task</h3>
<p class="doc-p">Complete a real task in conversation with an agent, providing context, corrections, and preferences along the way. Then extract the reusable pattern into a skill. Pay attention to:</p>
<ul class="doc-list">
<li><strong>Steps that worked</strong> — the sequence of actions that led to success</li>
<li><strong>Corrections you made</strong> — places where you steered the agent&#39;s approach (e.g., &quot;use library X instead of Y,&quot; &quot;check for edge case Z&quot;)</li>
<li><strong>Input/output formats</strong> — what the data looked like going in and coming out</li>
<li><strong>Context you provided</strong> — project-specific facts, conventions, or constraints the agent didn&#39;t already know</li>
</ul>
<h3 class="doc-h3">Synthesize from existing project artifacts</h3>
<p class="doc-p">When you have a body of existing knowledge, you can feed it into an LLM and ask it to synthesize a skill. A data-pipeline skill synthesized from your team&#39;s actual incident reports and runbooks will outperform one synthesized from a generic &quot;data engineering best practices&quot; article, because it captures <em>your</em> schemas, failure modes, and recovery procedures. The key is project-specific material, not generic references.</p>
<p class="doc-p">Good source material includes:</p>
<ul class="doc-list">
<li>Internal documentation, runbooks, and style guides</li>
<li>API specifications, schemas, and configuration files</li>
<li>Code review comments and issue trackers (captures recurring concerns and reviewer expectations)</li>
<li>Version control history, especially patches and fixes (reveals patterns through what actually changed)</li>
<li>Real-world failure cases and their resolutions</li>
</ul>
<h2 id="refine-with-real-execution" class="doc-h2">Refine with real execution</h2>
<p class="doc-p">The first draft of a skill usually needs refinement. Run the skill against real tasks, then feed the results — all of them, not just failures — back into the creation process. Ask: what triggered false positives? What was missed? What could be cut?</p>
<p class="doc-p">Even a single pass of execute-then-revise noticeably improves quality, and complex domains often benefit from several.</p>
<div class="callout accent doc-callout">Read agent execution traces, not just final outputs. If the agent wastes time on unproductive steps, common causes include instructions that are too vague (the agent tries several approaches before finding one that works), instructions that don't apply to the current task (the agent follows them anyway), or too many options presented without a clear default.</div>



<p class="doc-p">For a more structured approach to iteration, including test cases, assertions, and grading, see <a href="/docs/skills-evaluating" class="doc-link">Evaluating skill output quality</a>.</p>
<h2 id="spending-context-wisely" class="doc-h2">Spending context wisely</h2>
<p class="doc-p">Once a skill activates, its full <code>SKILL.md</code> body loads into the agent&#39;s context window alongside conversation history, system context, and other active skills. Every token in your skill competes for the agent&#39;s attention with everything else in that window.</p>
<h3 class="doc-h3">Add what the agent lacks, omit what it knows</h3>
<p class="doc-p">Focus on what the agent <em>wouldn&#39;t</em> know without your skill: project-specific conventions, domain-specific procedures, non-obvious edge cases, and the particular tools or APIs to use. You don&#39;t need to explain what a PDF is, how HTTP works, or what a database migration does.</p>
<div class="codeblock"><pre><code class="language-markdown">## PDF form filling

1. Extract form fields: \`python scripts/analyze_form.py input.pdf\` → \`form_fields.json\`
   (lists every field name, type, and whether it&#39;s required)
2. Create \`field_values.json\` mapping each field name to its intended value
3. Validate: \`python scripts/validate_fields.py form_fields.json field_values.json\`
   (checks that every field name exists in the form, types are compatible, and
   required fields aren&#39;t missing)
4. If validation fails, revise \`field_values.json\` and re-validate
5. Fill the form: \`python scripts/fill_form.py input.pdf field_values.json output.pdf\`
\`\`\`

The key ingredient is step 3: a validation script that checks the plan (\`field_values.json\`) against the source of truth (\`form_fields.json\`). Errors like &quot;Field &#39;signature\\_date&#39; not found — available fields: customer\\_name, order\\_total, signature\\_date\\_signed&quot; give the agent enough information to self-correct.

### Bundling reusable scripts

When [iterating on a skill](/skill-creation/evaluating-skills), compare the agent&#39;s execution traces across test cases. If you notice the agent independently reinventing the same logic each run — building charts, parsing a specific format, validating output — that&#39;s a signal to write a tested script once and bundle it in \`scripts/\`.

For more on designing and bundling scripts, see [Using scripts in skills](/skill-creation/using-scripts).

## Next steps

Once you have a working skill, two guides can help you refine it further:

* **[Evaluating skill output quality](/skill-creation/evaluating-skills)** — Set up test cases, grade results, and iterate systematically.
* **[Optimizing skill descriptions](/skill-creation/optimizing-descriptions)** — Test and improve your skill&#39;s \`description\` field so it triggers on the right prompts.
</code></pre></div>
`,
  },
  {
    id: 'skills-descriptions',
    section: 'agent-skills',
    title: "Optimizing skill descriptions",
    navLabel: "Skill descriptions",
    readTime: 3,
    updatedAt: '2026-06-01',
    lead: "How to improve your skill's description so it triggers reliably on relevant prompts.",
    body: `<h2 id="how-skill-triggering-works" class="doc-h2">How skill triggering works</h2>
<p class="doc-p">Agents use <a href="/docs/skills-specification#progressive-disclosure" class="doc-link">progressive disclosure</a> to manage context. At startup, they load only the <code>name</code> and <code>description</code> of each available skill — just enough to decide when a skill might be relevant. When a user&#39;s task matches a description, the agent reads the full <code>SKILL.md</code> into context and follows its instructions.</p>
<p class="doc-p">This means the description carries the entire burden of triggering. If the description doesn&#39;t convey when the skill is useful, the agent won&#39;t know to reach for it.</p>
<p class="doc-p">One important nuance: agents typically only consult skills for tasks that require knowledge or capabilities beyond what they can handle alone. A simple, one-step request like &quot;read this PDF&quot; may not trigger a PDF skill even if the description matches perfectly, because the agent can handle it with basic tools. Tasks that involve specialized knowledge — an unfamiliar API, a domain-specific workflow, or an uncommon format — are where a well-written description can make the difference.</p>
<h2 id="writing-effective-descriptions" class="doc-h2">Writing effective descriptions</h2>
<p class="doc-p">Before testing, it helps to know what a good description looks like. A few principles:</p>
<ul class="doc-list">
<li><strong>Use imperative phrasing.</strong> Frame the description as an instruction to the agent: &quot;Use this skill when...&quot; rather than &quot;This skill does...&quot; The agent is deciding whether to act, so tell it when to act.</li>
<li><strong>Focus on user intent, not implementation.</strong> Describe what the user is trying to achieve, not the skill&#39;s internal mechanics. The agent matches against what the user asked for.</li>
<li><strong>Err on the side of being pushy.</strong> Explicitly list contexts where the skill applies, including cases where the user doesn&#39;t name the domain directly: &quot;even if they don&#39;t explicitly mention &#39;CSV&#39; or &#39;analysis.&#39;&quot;</li>
<li><strong>Keep it concise.</strong> A few sentences to a short paragraph is usually right — long enough to cover the skill&#39;s scope, short enough that it doesn&#39;t bloat the agent&#39;s context across many skills. The <a href="/docs/skills-specification#description-field" class="doc-link">specification</a> enforces a hard limit of 1024 characters.</li>
</ul>
<h2 id="designing-trigger-eval-queries" class="doc-h2">Designing trigger eval queries</h2>
<p class="doc-p">To test triggering, you need a set of eval queries — realistic user prompts labeled with whether they should or shouldn&#39;t trigger your skill.</p>
<div class="codeblock"><pre><code class="language-json"># Before
description: Process CSV files.

# After
description: &gt;
  Analyze CSV and tabular data files — compute summary statistics,
  add derived columns, generate charts, and clean messy data. Use this
  skill when the user has a CSV, TSV, or Excel file and wants to
  explore, transform, or visualize the data, even if they don&#39;t
  explicitly mention &quot;CSV&quot; or &quot;analysis.&quot;
</code></pre></div>
<p class="doc-p">The improved description is more specific about what the skill does (summary stats, derived columns, charts, cleaning) and broader about when it applies (CSV, TSV, Excel; even without explicit keywords).</p>
<h2 id="next-steps" class="doc-h2">Next steps</h2>
<p class="doc-p">Once your skill triggers reliably, you&#39;ll want to evaluate whether it produces good outputs. See <a href="/docs/skills-evaluating" class="doc-link">Evaluating skill output quality</a> for how to set up test cases, grade results, and iterate.</p>
`,
  },
  {
    id: 'skills-scripts',
    section: 'agent-skills',
    title: "Using scripts in skills",
    navLabel: "Using scripts",
    readTime: 3,
    updatedAt: '2026-06-01',
    lead: "How to run commands and bundle executable scripts in your skills.",
    body: `<h2 id="one-off-commands" class="doc-h2">One-off commands</h2>
<p class="doc-p">When an existing package already does what you need, you can reference it directly in your <code>SKILL.md</code> instructions without a <code>scripts/</code> directory. Many ecosystems provide tools that auto-resolve dependencies at runtime.</p>
<h3 class="doc-h3">uvx</h3>
<p class="doc-p"><a href="https://docs.astral.sh/uv/guides/tools/" class="doc-link">uvx</a> runs Python packages in isolated environments with aggressive caching. It ships with <a href="https://docs.astral.sh/uv/" class="doc-link">uv</a>.</p>
<div class="codeblock"><pre><code>\`\`\`bash
ruby scripts/extract.rb
\`\`\`

* Pin versions explicitly (\`gem &#39;nokogiri&#39;, &#39;~&gt; 1.16&#39;\`) — there is no lockfile.
* An existing \`Gemfile\` or \`BUNDLE_GEMFILE\` env var in the working directory can interfere.
</code></pre></div>
<h2 id="designing-scripts-for-agentic-use" class="doc-h2">Designing scripts for agentic use</h2>
<p class="doc-p">When an agent runs your script, it reads stdout and stderr to decide what to do next. A few design choices make scripts dramatically easier for agents to use.</p>
<h3 class="doc-h3">Avoid interactive prompts</h3>
<p class="doc-p">This is a hard requirement of the agent execution environment. Agents operate in non-interactive shells — they cannot respond to TTY prompts, password dialogs, or confirmation menus. A script that blocks on interactive input will hang indefinitely.</p>
<p class="doc-p">Accept all input via command-line flags, environment variables, or stdin:</p>
<div class="codeblock"><pre><code># Bad: hangs waiting for input
$ python scripts/deploy.py
Target environment: _

# Good: clear error with guidance
$ python scripts/deploy.py
Error: --env is required. Options: development, staging, production.
Usage: python scripts/deploy.py --env staging --tag v1.2.3
</code></pre></div>
<h3 class="doc-h3">Document usage with <code>--help</code></h3>
<p class="doc-p"><code>--help</code> output is the primary way an agent learns your script&#39;s interface. Include a brief description, available flags, and usage examples:</p>
<div class="codeblock"><pre><code>Usage: scripts/process.py [OPTIONS] INPUT_FILE

Process input data and produce a summary report.

Options:
  --format FORMAT    Output format: json, csv, table (default: json)
  --output FILE      Write output to FILE instead of stdout
  --verbose          Print progress to stderr

Examples:
  scripts/process.py data.csv
  scripts/process.py --format csv --output report.csv data.csv
</code></pre></div>
<p class="doc-p">Keep it concise — the output enters the agent&#39;s context window alongside everything else it&#39;s working with.</p>
<h3 class="doc-h3">Write helpful error messages</h3>
<p class="doc-p">When an agent gets an error, the message directly shapes its next attempt. An opaque &quot;Error: invalid input&quot; wastes a turn. Instead, say what went wrong, what was expected, and what to try:</p>
<div class="codeblock"><pre><code>Error: --format must be one of: json, csv, table.
       Received: &quot;xml&quot;
</code></pre></div>
<h3 class="doc-h3">Use structured output</h3>
<p class="doc-p">Prefer structured formats — JSON, CSV, TSV — over free-form text. Structured formats can be consumed by both the agent and standard tools (<code>jq</code>, <code>cut</code>, <code>awk</code>), making your script composable in pipelines.</p>
<div class="codeblock"><pre><code># Whitespace-aligned — hard to parse programmatically
NAME          STATUS    CREATED
my-service    running   2025-01-15

# Delimited — unambiguous field boundaries
{&quot;name&quot;: &quot;my-service&quot;, &quot;status&quot;: &quot;running&quot;, &quot;created&quot;: &quot;2025-01-15&quot;}
</code></pre></div>
<p class="doc-p"><strong>Separate data from diagnostics:</strong> send structured data to stdout and progress messages, warnings, and other diagnostics to stderr. This lets the agent capture clean, parseable output while still having access to diagnostic information when needed.</p>
<h3 class="doc-h3">Further considerations</h3>
<ul class="doc-list">
<li><strong>Idempotency.</strong> Agents may retry commands. &quot;Create if not exists&quot; is safer than &quot;create and fail on duplicate.&quot;</li>
<li><strong>Input constraints.</strong> Reject ambiguous input with a clear error rather than guessing. Use enums and closed sets where possible.</li>
<li><strong>Dry-run support.</strong> For destructive or stateful operations, a <code>--dry-run</code> flag lets the agent preview what will happen.</li>
<li><strong>Meaningful exit codes.</strong> Use distinct exit codes for different failure types (not found, invalid arguments, auth failure) and document them in your <code>--help</code> output so the agent knows what each code means.</li>
<li><strong>Safe defaults.</strong> Consider whether destructive operations should require explicit confirmation flags (<code>--confirm</code>, <code>--force</code>) or other safeguards appropriate to the risk level.</li>
<li><strong>Predictable output size.</strong> Many agent harnesses automatically truncate tool output beyond a threshold (e.g., 10-30K characters), potentially losing critical information. If your script might produce large output, default to a summary or a reasonable limit, and support flags like <code>--offset</code> so the agent can request more information when needed. Alternatively, if output is large and not amenable to pagination, require agents to pass an <code>--output</code> flag that specifies either an output file or <code>-</code> to explicitly opt in to stdout.</li>
</ul>
`,
  },
  {
    id: 'skills-evaluating',
    section: 'agent-skills',
    title: "Evaluating skill output quality",
    navLabel: "Evaluating skills",
    readTime: 3,
    updatedAt: '2026-06-01',
    lead: "How to test whether your skill produces good outputs using eval-driven iteration.",
    body: `<h2 id="designing-test-cases" class="doc-h2">Designing test cases</h2>
<p class="doc-p">A test case has three parts:</p>
<ul class="doc-list">
<li><strong>Prompt</strong>: a realistic user message — the kind of thing someone would actually type.</li>
<li><strong>Expected output</strong>: a human-readable description of what success looks like.</li>
<li><strong>Input files</strong> (optional): files the skill needs to work with.</li>
</ul>
<p class="doc-p">Store test cases in <code>evals/evals.json</code> inside your skill directory:</p>
<div class="codeblock"><pre><code class="language-json">{
  &quot;eval-top-months-chart&quot;: &quot;The chart is missing axis labels and the months are in alphabetical order instead of chronological.&quot;,
  &quot;eval-clean-missing-emails&quot;: &quot;&quot;
}
</code></pre></div>
<p class="doc-p">&quot;The chart is missing axis labels&quot; is actionable; &quot;looks bad&quot; is not. Empty feedback means the output looked fine — that test case passed your review. During the <a href="#iterating-on-the-skill#iterating-on-the-skill" class="doc-link">iteration step</a>, focus your improvements on the test cases where you had specific complaints.</p>
<h2 id="iterating-on-the-skill" class="doc-h2">Iterating on the skill</h2>
<p class="doc-p">After grading and reviewing, you have three sources of signal:</p>
<ul class="doc-list">
<li><strong>Failed assertions</strong> point to specific gaps — a missing step, an unclear instruction, or a case the skill doesn&#39;t handle.</li>
<li><strong>Human feedback</strong> points to broader quality issues — the approach was wrong, the output was poorly structured, or the skill produced a technically correct but unhelpful result.</li>
<li><strong>Execution transcripts</strong> reveal <em>why</em> things went wrong. If the agent ignored an instruction, the instruction may be ambiguous. If the agent spent time on unproductive steps, those instructions may need to be simplified or removed.</li>
</ul>
<p class="doc-p">The most effective way to turn these signals into skill improvements is to give all three — along with the current <code>SKILL.md</code> — to an LLM and ask it to propose changes. The LLM can synthesize patterns across failed assertions, reviewer complaints, and transcript behavior that would be tedious to connect manually. When prompting the LLM, include these guidelines:</p>
<ul class="doc-list">
<li><strong>Generalize from feedback.</strong> The skill will be used across many different prompts, not just the test cases. Fixes should address underlying issues broadly rather than adding narrow patches for specific examples.</li>
<li><strong>Keep the skill lean.</strong> Fewer, better instructions often outperform exhaustive rules. If transcripts show wasted work (unnecessary validation, unneeded intermediate outputs), remove those instructions. If pass rates plateau despite adding more rules, the skill may be over-constrained — try removing instructions and see if results hold or improve.</li>
<li><strong>Explain the why.</strong> Reasoning-based instructions (&quot;Do X because Y tends to cause Z&quot;) work better than rigid directives (&quot;ALWAYS do X, NEVER do Y&quot;). Models follow instructions more reliably when they understand the purpose.</li>
<li><strong>Bundle repeated work.</strong> If every test run independently wrote a similar helper script (a chart builder, a data parser), that&#39;s a signal to bundle the script into the skill&#39;s <code>scripts/</code> directory. See <a href="/docs/skills-scripts" class="doc-link">Using scripts</a> for how to do this.</li>
</ul>
<h3 class="doc-h3">The loop</h3>
<ol class="doc-steps">
<li>Give the eval signals and current <code>SKILL.md</code> to an LLM and ask it to propose improvements.</li>
<li>Review and apply the changes.</li>
<li>Rerun all test cases in a new <code>iteration-&lt;N+1&gt;/</code> directory.</li>
<li>Grade and aggregate the new results.</li>
<li>Review with a human. Repeat.</li>
</ol>
<p class="doc-p">Stop when you&#39;re satisfied with the results, feedback is consistently empty, or you&#39;re no longer seeing meaningful improvement between iterations.</p>
<div class="callout accent doc-callout">The [\`skill-creator\`](https://github.com/anthropics/skills/tree/main/skills/skill-creator) Skill automates much of this workflow — running evals, grading assertions, aggregating benchmarks, and presenting results for human review.</div>`,
  },
];
